// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_cVk0kxlYFcs388U5ZMEyuCE58xkJkWI',
    appId: '1:220421475216:web:7d6ed762b0c410500fc115',
    messagingSenderId: '220421475216',
    projectId: 'sixvalley-3cd02',
    authDomain: 'sixvalley-3cd02.firebaseapp.com',
    storageBucket: 'sixvalley-3cd02.firebasestorage.app',
    measurementId: 'G-LBTMRFCC70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG6iZz_O5YTmHVKikPWbdcZPMQn6xSMEo',
    appId: '1:220421475216:android:af2fea292c5dff860fc115',
    messagingSenderId: '220421475216',
    projectId: 'sixvalley-3cd02',
    storageBucket: 'sixvalley-3cd02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFpU5wN3X0ChxDBKj0YTNy-IutOJJR8K0',
    appId: '1:220421475216:ios:b7415d7da1df7ac00fc115',
    messagingSenderId: '220421475216',
    projectId: 'sixvalley-3cd02',
    storageBucket: 'sixvalley-3cd02.firebasestorage.app',
    iosBundleId: 'com.example.sixvalley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFpU5wN3X0ChxDBKj0YTNy-IutOJJR8K0',
    appId: '1:220421475216:ios:b7415d7da1df7ac00fc115',
    messagingSenderId: '220421475216',
    projectId: 'sixvalley-3cd02',
    storageBucket: 'sixvalley-3cd02.firebasestorage.app',
    iosBundleId: 'com.example.sixvalley',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_cVk0kxlYFcs388U5ZMEyuCE58xkJkWI',
    appId: '1:220421475216:web:36baaf528f1fccc10fc115',
    messagingSenderId: '220421475216',
    projectId: 'sixvalley-3cd02',
    authDomain: 'sixvalley-3cd02.firebaseapp.com',
    storageBucket: 'sixvalley-3cd02.firebasestorage.app',
    measurementId: 'G-N7J5NB2L6J',
  );
}
